import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CircleMarker, MapContainer, Popup, TileLayer } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import api from "../../services/api";
import "./AdminDashboard.css";

const tabs = [["dashboard","Dashboard"],["users","User Management"],["drivers","Driver Approval"],["operators","Operator Approval"],["buses","Bus Approval"],["routes","Route Management"],["trips","Trip Monitoring"],["fleet","Live Fleet Map"],["complaints","Complaints / Issues"],["feedback","Feedback Management"],["notifications","Notifications"],["reports","Reports & Analytics"],["audit","Audit Logs"],["settings","Admin Settings"]];
const endpoint = { dashboard:"dashboard", users:"users", drivers:"approvals/drivers", operators:"approvals/operators", buses:"approvals/buses", routes:"routes", trips:"trips", fleet:"fleet", complaints:"complaints", feedback:"feedback", notifications:"notifications", reports:"reports", audit:"audit-logs", settings:"settings" };

export default function AdminDashboard() {
  const navigate=useNavigate(), [tab,setTab]=useState("dashboard"), [data,setData]=useState({}), [loading,setLoading]=useState(true), [error,setError]=useState("");
  const load=useCallback(async (section=tab)=>{setLoading(true);setError("");try{const result=await api.get(`/admin/${endpoint[section]}`);setData((current)=>({...current,[section]:result.data}));}catch(err){if([401,403].includes(err.response?.status))navigate("/admin/login");else setError(err.response?.data?.message||"Unable to load this module.");}finally{setLoading(false);}},[tab,navigate]);
  useEffect(()=>{load(tab);},[tab,load]);
  const action=async(method,url,section,body={})=>{try{await api({method,url, data:body});await load(section);}catch(err){setError(err.response?.data?.message||"Action failed.");}};
  const logout=()=>{localStorage.removeItem("busMitraToken");localStorage.removeItem("busMitraUser");navigate("/admin/login");};
  const recordRows=()=>{const section=data[tab]||{};return section.users||section.buses||section.routes||section.trips||section.fleet||section.complaints||section.feedback||section.notifications||section.logs||[];};
  return <main className="admin-dashboard"><aside><div className="admin-brand">Bus Mitra<span>Super Admin</span></div><nav>{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav><button className="admin-logout" onClick={logout}>Log out</button></aside><section className="admin-content"><header><div><p>Platform control centre</p><h1>{tabs.find(([key])=>key===tab)?.[1]}</h1></div><button onClick={()=>load()}>Refresh</button></header>{error&&<p className="admin-error">{error}</p>}{loading?<p>Loading...</p>:<>{tab==="dashboard"&&<Stats stats={data.dashboard?.stats}/>} {tab==="reports"&&<Reports report={data.reports?.report}/>} {tab==="settings"&&<Settings admin={data.settings?.admin} action={action}/>} {tab==="notifications"&&<NotificationPanel rows={recordRows()} action={action} refresh={load}/>} {tab==="fleet"&&<FleetMap fleet={data.fleet?.fleet}/>} {!['dashboard','reports','settings','notifications','fleet'].includes(tab)&&<Records tab={tab} rows={recordRows()} action={action}/>}</>}</section></main>;
}
function Stats({stats={}}){return <div className="admin-stats">{Object.entries(stats).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></article>)}</div>}
function Records({tab,rows,action}){if(!rows.length)return <div className="admin-empty">No records to show.</div>;return <div className="admin-records">{rows.map((row)=><article key={row._id}><div><strong>{row.name||row.busNumber||row.routeName||row.subject||row.title||row.action||"Record"}</strong><p>{row.email||row.registrationNumber||`${row.origin||""} ${row.destination?`→ ${row.destination}`:""}`||row.message||row.details||""}</p><small>{row.role||row.status||row.createdAt}</small></div>{["drivers","operators"].includes(tab)&&<button onClick={()=>action("patch",`/admin/approvals/users/${row._id}`,tab)}>Approve</button>}{tab==="buses"&&<button onClick={()=>action("patch",`/admin/approvals/buses/${row._id}`,tab)}>Approve</button>}{tab==="routes"&&row.isApproved===false&&<button onClick={()=>action("patch",`/admin/routes/${row._id}/approve`,tab)}>Approve</button>}{tab==="users"&&<button onClick={()=>action("patch",`/admin/users/${row._id}/status`,tab,{isActive:!row.isActive})}>{row.isActive?"Deactivate":"Activate"}</button>}{tab==="complaints"&&row.status!=="resolved"&&<button onClick={()=>action("patch",`/admin/complaints/${row._id}`,tab,{status:"resolved"})}>Resolve</button>}</article>)}</div>}
function Reports({report={}}){return <div className="admin-report"><h2>Trips by status</h2>{report.tripStatus?.map((x)=><p key={x._id}>{x._id}<strong>{x.count}</strong></p>)}<h2>Users by role</h2>{report.usersByRole?.map((x)=><p key={x._id}>{x._id}<strong>{x.count}</strong></p>)}</div>}
function FleetMap({fleet=[]}){const buses=fleet.filter((trip)=>Number.isFinite(trip.bus?.currentLocation?.latitude)&&Number.isFinite(trip.bus?.currentLocation?.longitude));if(!buses.length)return <div className="admin-empty">No running buses with live GPS coordinates.</div>;const center=[buses[0].bus.currentLocation.latitude,buses[0].bus.currentLocation.longitude];return <div style={{height:540,border:"1px solid #e2e8f0",borderRadius:11,overflow:"hidden"}}><MapContainer style={{height:"100%",width:"100%"}} center={center} zoom={12} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{buses.map((trip)=><CircleMarker key={trip._id} center={[trip.bus.currentLocation.latitude,trip.bus.currentLocation.longitude]} radius={9} pathOptions={{color:"#2563eb"}}><Popup><strong>{trip.bus.busNumber}</strong><br />{trip.driver?.name}<br />{trip.route?.origin} → {trip.route?.destination}</Popup></CircleMarker>)}</MapContainer></div>}
function NotificationPanel({rows,action,refresh}){const [form,setForm]=useState({userId:"",title:"",message:""});return <><form className="admin-notification-form" onSubmit={(e)=>{e.preventDefault();action("post","/admin/notifications","notifications",form);setForm({userId:"",title:"",message:""});}}><h2>Send notification</h2>{[["userId","Recipient user ID"],["title","Title"],["message","Message"]].map(([key,label])=><label key={key}>{label}<input required value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></label>)}<button>Send</button></form><Records tab="notifications" rows={rows} action={action}/></>}
function Settings({admin,action}){const [form,setForm]=useState({name:admin?.name||"",phone:admin?.phone||"",profileImage:admin?.profileImage||""});useEffect(()=>setForm({name:admin?.name||"",phone:admin?.phone||"",profileImage:admin?.profileImage||""}),[admin]);return <form className="admin-notification-form" onSubmit={(e)=>{e.preventDefault();action("put","/admin/settings","settings",form);}}><h2>Admin profile</h2>{[["name","Name"],["phone","Phone"],["profileImage","Profile image URL"]].map(([key,label])=><label key={key}>{label}<input value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></label>)}<button>Save settings</button></form>}
