import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FaBell, FaBus, FaClock, FaEye, FaEyeSlash, FaHeart, FaLock, FaMapMarkerAlt, FaShieldAlt } from "react-icons/fa";
import authService from "../../services/authService";
import busImage from "../../assets/images/bus.png";
import "./Login.css";

export default function Login() {
  const navigate=useNavigate(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[show,setShow]=useState(false);
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError("");try{const data=await authService.login({email,password});if(data.user.role!=="passenger"){authService.logout();throw new Error("Please use your dedicated operator or admin login.");}navigate("/dashboard");}catch(err){setError(err.response?.data?.message||err.message||"Unable to log in.");}finally{setLoading(false);}};
  return <main className="login-modern"><section className="login-visual"><Link to="/" className="login-brand"><span><FaBus/></span><b>Bus <em>Mitra</em></b></Link><h1>Welcome Back!</h1><p>Login to continue your journey with real-time bus tracking.</p><img src={busImage} alt="Bus Mitra bus"/><div className="login-benefits">{[[<FaMapMarkerAlt/>,"Live Bus Tracking","Track your bus in real-time on live map"],[<FaClock/>,"Accurate ETA","Get accurate arrival time at your stop"],[<FaBell/>,"Smart Alerts","Receive alerts for arrivals, delays & updates"],[<FaHeart/>,"Save Favorites","Save routes and buses for quick access"]].map(([i,t,d])=><article key={t}><i>{i}</i><div><b>{t}</b><span>{d}</span></div></article>)}</div><small><FaShieldAlt/> Your data is <b>safe and secure</b> with us.</small></section><section className="login-card"><div className="login-language">◎ English⌄</div><h2>Login</h2><p>Login to your account</p><div className="login-tabs"><b>Login</b><Link to="/register">Sign Up</Link></div><form onSubmit={submit}><label>Email or Phone Number<div><span>✉</span><input required type="email" placeholder="Enter your email or phone number" value={email} onChange={e=>setEmail(e.target.value)}/></div></label><label>Password<div><span><FaLock/></span><input required type={show?"text":"password"} placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setShow(!show)}>{show?<FaEyeSlash/>:<FaEye/>}</button></div></label><Link className="forgot" to="/contact">Forgot Password?</Link>{error&&<div className="login-error">{error}</div>}<label className="remember"><input type="checkbox" defaultChecked/> Remember me</label><button className="login-submit" disabled={loading}>{loading?"Logging in...":"Login  →"}</button></form><div className="divider">or continue with</div><div className="social-login"><button>🇬 Continue with Google</button><button>☎ Continue with Mobile</button></div><p className="terms"><FaShieldAlt/> By logging in, you agree to our <Link to="/about">Terms & Conditions</Link> and <Link to="/about">Privacy Policy</Link></p></section></main>;
}
