import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FaBell, FaBus, FaClock, FaHeart, FaMapMarkerAlt, FaRegHeart, FaRoad, FaSearch, FaSlidersH, FaStar, FaUserCircle } from "react-icons/fa";
import favoriteService from "../../services/favoriteService";
import tripService from "../../services/tripService";
import busImage from "../../assets/images/bus.png";
import "./Favorites.css";

export default function Favorites() {
  const navigate = useNavigate(); const [favorites, setFavorites] = useState([]); const [trips, setTrips] = useState([]); const [tab, setTab] = useState("routes"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [removing, setRemoving] = useState("");
  useEffect(() => { const load = async () => { try { setLoading(true); const [favoriteData, tripData] = await Promise.all([favoriteService.getFavorites(), tripService.getTrips({ limit: 100 })]); setFavorites(favoriteData.favorites || []); setTrips(tripData.trips || []); } catch (requestError) { if (requestError.response?.status === 401) navigate("/login"); else setError(requestError.response?.data?.message || "Unable to load favorites"); } finally { setLoading(false); } }; load(); }, [navigate]);
  const routeFavorites = favorites.filter((item) => item.type === "route" && item.route); const busFavorites = favorites.filter((item) => item.type === "bus" && item.bus);
  const liveTripFor = (busId) => trips.find((trip) => String(trip.bus?._id || trip.bus) === String(busId) && ["running", "boarding", "paused"].includes(trip.status));
  const remove = async (id) => { try { setRemoving(id); await favoriteService.removeFavorite(id); setFavorites((current) => current.filter((favorite) => favorite._id !== id)); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to remove favorite"); } finally { setRemoving(""); } };
  if (loading) return <div className="favorites-state">Loading your saved routes and buses…</div>;
  if (error && !favorites.length) return <div className="favorites-state"><h2>Unable to load favorites</h2><p>{error}</p><button onClick={() => window.location.reload()}>Try Again</button></div>;
  return <main className="favorites-modern"><header className="favorites-topbar"><button aria-label="Menu"><FaSlidersH /></button><Link to="/" className="favorites-brand"><span><FaBus /></span><b>Bus <em>Mitra</em></b></Link><div><Link to="/search-bus" aria-label="Search"><FaSearch /></Link><button aria-label="Notifications"><FaBell /></button><Link to="/profile" aria-label="Profile"><FaUserCircle /></Link></div></header><section className="favorites-hero"><i><FaHeart /></i><div><h1>Favorites</h1><p>Your saved routes and buses for quick access</p></div><button><FaSlidersH /> Manage</button></section><section className="favorites-tabs"><button className={tab === "routes" ? "active" : ""} onClick={() => setTab("routes")}><FaRoad /> Saved Routes <b>{routeFavorites.length}</b></button><button className={tab === "buses" ? "active" : ""} onClick={() => setTab("buses")}><FaBus /> Saved Buses <b>{busFavorites.length}</b></button></section>{tab === "routes" ? <RoutesSection routes={routeFavorites} remove={remove} removing={removing} navigate={navigate} /> : <BusesSection buses={busFavorites} remove={remove} removing={removing} navigate={navigate} liveTripFor={liveTripFor} />}<section className="favorites-bus-preview"><div className="favorites-preview-head"><h2>Saved Buses</h2><button onClick={() => { setTab("buses"); window.scrollTo({ top: 0, behavior: "smooth" }); }}>+ Add Bus</button></div>{busFavorites.length ? <div className="saved-bus-grid">{busFavorites.slice(0, 4).map((favorite) => <BusTile key={favorite._id} favorite={favorite} navigate={navigate} liveTrip={liveTripFor(favorite.bus._id)} />)}</div> : <p className="favorites-hint">Save a bus from its Bus Details page for quick live tracking.</p>}</section><section className="favorites-banner"><img src={busImage} alt="Bus"/><div><b>Track your favorites instantly</b><span>Get real-time updates and never miss your bus.</span></div><Link to="/routes">Explore Routes ›</Link></section><nav className="favorites-nav"><Link to="/dashboard"><FaUserCircle />Home</Link><Link to="/search-bus"><FaSearch />Search</Link><Link to="/nearby-buses"><FaMapMarkerAlt />Track Bus</Link><Link className="active" to="/favorites"><FaHeart />Favorites</Link><Link to="/profile"><FaUserCircle />Profile</Link></nav></main>;
}
function RoutesSection({ routes, remove, removing, navigate }) { return <section className="favorite-routes"><div className="favorite-section-head"><h2>Saved Routes</h2><Link to="/routes">+ Add Route</Link></div>{routes.length ? routes.map((favorite, index) => <article className="favorite-route-card" key={favorite._id}><i className={`favorite-route-icon c${index % 5}`}><FaRoad /></i><div className="favorite-route-main"><h3>{favorite.route.origin} <span>→</span> {favorite.route.destination}</h3><p>{favorite.route.routeNumber || "Route"} <b>•</b> {favorite.route.routeName || "Bus Mitra"}</p><div><span><FaRoad /> {favorite.route.distanceKm ?? "—"} km</span><span><FaClock /> {duration(favorite.route.estimatedDurationMinutes)}</span><span><FaBus /> Route</span></div></div><div className="favorite-route-time"><b>● Route Saved</b><div><span>First Bus<strong>{favorite.route.firstBusTime || "—"}</strong></span><span>Last Bus<strong>{favorite.route.lastBusTime || "—"}</strong></span></div></div><button className="heart-remove" onClick={() => remove(favorite._id)} disabled={removing === favorite._id}>{removing === favorite._id ? "…" : <FaHeart />}</button><button className="track-now" onClick={() => navigate(`/route/${favorite.route._id}`)}>View Route</button></article>) : <Empty icon={<FaRoad />} text="No saved routes yet" action="Explore Routes" to="/routes" />}</section>; }
function BusesSection({ buses, remove, removing, navigate, liveTripFor }) { return <section className="favorite-routes"><div className="favorite-section-head"><h2>Saved Buses</h2><Link to="/search-bus">+ Add Bus</Link></div>{buses.length ? buses.map((favorite) => { const trip = liveTripFor(favorite.bus._id); return <article className="favorite-route-card favorite-bus-row" key={favorite._id}><img src={busImage} alt="Bus"/><div className="favorite-route-main"><h3>{favorite.bus.busNumber}</h3><p>{favorite.bus.registrationNumber || "Saved Bus"} <b>•</b> {favorite.bus.busType || "Bus"}</p><div><span><FaMapMarkerAlt /> {trip?.nextStop?.name || "Location updates available"}</span></div></div><div className="favorite-route-time"><b className={trip ? "live" : ""}>● {trip ? "Live Tracking" : "Saved Bus"}</b><div><span>Speed<strong>{trip?.currentSpeed ? `${trip.currentSpeed} km/h` : "—"}</strong></span></div></div><button className="heart-remove" onClick={() => remove(favorite._id)} disabled={removing === favorite._id}>{removing === favorite._id ? "…" : <FaHeart />}</button><button className="track-now" onClick={() => trip ? navigate(`/track-bus?trip=${trip._id}`) : navigate(`/bus/${favorite.bus._id}`)}>{trip ? "Track Now" : "View Bus"}</button></article>; }) : <Empty icon={<FaBus />} text="No saved buses yet" action="Search Buses" to="/search-bus" />}</section>; }
function BusTile({ favorite, navigate, liveTrip }) { return <article><div><img src={busImage} alt="Bus"/><span>{liveTrip ? "Live" : "Saved"}</span><i><FaStar /></i></div><h3>{favorite.bus.busNumber}</h3><p>{favorite.bus.busType || "Bus"}</p><small><FaMapMarkerAlt /> {liveTrip?.nextStop?.name || "Saved for quick access"}</small><button onClick={() => liveTrip ? navigate(`/track-bus?trip=${liveTrip._id}`) : navigate(`/bus/${favorite.bus._id}`)}>⌾ {liveTrip ? "Track Live" : "View Bus"}</button></article>; }
function Empty({ icon, text, action, to }) { return <div className="favorite-empty"><i>{icon}</i><h3>{text}</h3><Link to={to}>{action}</Link></div>; }
function duration(value) { return value ? `${Math.floor(value / 60)}h ${value % 60}m` : "—"; }
